services:
  server:
    image: server
    build:
      context: ./
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
